name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#workflow level env variables
env:
  APP_NAME: customer-support-portal

  
jobs:
  build:
    name: NodeJS Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Node.js 24
      uses: actions/setup-node@v6
      with:
          node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Show trigger, app, and branch
      run: |
          echo "App   : $APP_NAME"
          echo "Event : ${{ github.event_name }}"
          echo "Ref   : $GITHUB_REF"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: support-portal-package
        path: |
          server.js
          package.json
          package-lock.json
          src/
          dist/
        retention-days: 2
      
 
    
