name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#workflow level env variables
env:
  APP_NAME: customer-support-portal
  AZURE_WEBAPP_NAME: customersupport2026

  
jobs:
  build:
    name: NodeJS Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Set up Node.js 24
      uses: actions/setup-node@v6
      with:
          node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Show trigger, app, and branch
      run: |
          echo "App   : $APP_NAME"
          echo "Event : ${{ github.event_name }}"
          echo "Ref   : $GITHUB_REF"

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: support-portal-package
        path: |
          server.js
          package.json
          package-lock.json
          src/
          dist/
        retention-days: 2
      
  deploy:
    name: Deploy to Azure WebApp
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ vars.AZURE_WEBAPP_NAME}}.azurewebsites.net

    steps:
      - name: Download Deployment Artifact
        uses: actions/download-artifact@v8.0.0
        with:
          name: support-portal-package
          path: app

      - name: Deploy to Azure App Service
        uses: Azure/webapps-deploy@v3.0.7
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: app
    
    
